export const arrayCountry = [
  { capital: 'Kiev', country: 'Ukraine' },
  { capital: 'London', country: 'United Kingdom' },
  { capital: 'Paris', country: 'France' },
  { capital: 'Berlin', country: 'Germany' },
  { capital: 'Rome', country: 'Italy' },
  { capital: 'Madrid', country: 'Spain' },
  { capital: 'Lisbon', country: 'Portugal' },
  { capital: 'Athens', country: 'Greece' },
  { capital: 'Stockholm', country: 'Sweden' },
  { capital: 'Oslo', country: 'Norway' },
  { capital: 'Copenhagen', country: 'Denmark' },
  { capital: 'Helsinki', country: 'Finland' },
  { capital: 'Warsaw', country: 'Poland' },
  { capital: 'Vienna', country: 'Austria' },
  { capital: 'Brussels', country: 'Belgium' },
  { capital: 'Amsterdam', country: 'Netherlands' },
  { capital: 'Dublin', country: 'Ireland' },
  { capital: 'Budapest', country: 'Hungary' },
  { capital: 'Prague', country: 'Czech Republic' },
  { capital: 'Bratislava', country: 'Slovakia' },
  { capital: 'Ljubljana', country: 'Slovenia' },
  { capital: 'Zagreb', country: 'Croatia' },
  { capital: 'Sarajevo', country: 'Bosnia and Herzegovina' },
  { capital: 'Belgrade', country: 'Serbia' },
  { capital: 'Skopje', country: 'North Macedonia' },
  { capital: 'Tirana', country: 'Albania' },
  { capital: 'Podgorica', country: 'Montenegro' },
  { capital: 'Pristina', country: 'Kosovo' },
  { capital: 'Vatican City', country: 'Vatican City' },
  { capital: 'Sofia', country: 'Bulgaria' },
  { capital: 'Bucharest', country: 'Romania' },
  { capital: 'Chisinau', country: 'Moldova' },
  { capital: 'Ankara', country: 'Turkey' },
];
